### ISSUE TITLE
the firewall dislikes HTML

### ISSUE THREAD

**Issue by xkitten** [Kak2X/BoardC#2]
After attempting to make a thread using a href because BBcode wasn't implemented, the firewall blocked me from doing that, sending me to a Forbidden page.

**Comment by Kak2X** [comment]
there's nothing that should block you from doing that. even if I did provide firewall.php, it wouldn't block that kind of stuff - I tested it in my local copy and I didn't get blocked

I assume it's something related to the hosting provider, but I may be wrong

**Comment by Yushe** [comment]
@Kak2X It most likely is something to do with @xkitten's hosting provider because @xkitten uses free hosts.
